name: SMPBuildWorld
version: '1.0-SNAPSHOT'
main: me.devvy.smpbuildworld.SMPBuildWorld
api-version: '1.20'

commands:
  buildworld:
    description: Set of commands used to interact with build world!
