name: DynamicDifficulty
version: '${project.version}'
main: me.devvy.dynamicdifficulty.DynamicDifficulty
api-version: '1.20'
commands:
  difficulty:
    description: Sets difficulty preference for the player
    usage: /<command> <difficulty>