# The max skill level that can be achieved naturally. Works as an effective skill "cap".
# Skill rewards will not be initialized past this point either, so setting a skill cap and setting a user's
# skill level to surpass it will result in no rewards.
max-skill-level: 100

# The skill level required in order to enter the Nether.
nether-skill-unlock: 15

# The skill level required in order to enter The End.
end-skill-unlock: 30

# Set these if you want certain dimensions to be locked behind average skill requirements.
# If you don't want dimensions to be level locked, then set them to 0.
# Keep in mind that players on "Easy" (Wanderer) can bypass this.
world_skill_unlocks:
  nether: 15
  end: 30

# Set these to when you want certain dimensions to be accessible.
# If you want them to always be accessible, just set it to some past date.
# Players playing on "Easy" (Wanderer) will be locked behind these as well.
world_time_unlocks:
  nether: "2025-01-01T00:00:00Z"
  end: "2025-01-01T00:00:00Z"