name: SMPRPG
version: '${version}'
main: xyz.devvydont.smprpg.SMPRPG
bootstrapper: xyz.devvydont.smprpg.SMPRPGBootstrapper
api-version: '1.21'

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    ProtocolLib:
      load: BEFORE
      required: true