name: AdvancementCompetition
version: '${project.version}'
main: me.devvy.advancementcompetition.AdvancementCompetition
api-version: '1.20'

commands:
  togglescoreboard:
    description: Toggles display mode of advancement scoreboard
