name: SMPMobArena
version: '${version}'
main: me.devvy.smpmobarena.SMPMobArena
api-version: '1.20'

depend:
  - BetterScoreboards

commands:
  mobarena:
    description: Main command for mob arena
    usage: /mobarena <subcommand> [args]

