name: Stimmys
version: '1.0-SNAPSHOT'
main: me.devvy.stimmys.Stimmys
api-version: '1.20'
commands:
  stimmy:
    description: Use/redeem stimmies from participating in events
    usage: /stimmy < redeem | shop >