name: SMPEvents
version: '${project.version}'
main: me.devvy.smpevents.SMPEvents
api-version: '1.20'
softdepend:
  - DeathDrops
  - SMPDuels
  - Dodgebolt
  - SMPParkour
  - Stimmys

commands:
  event:
    description: Teleport to the event hub!
